/**
 * InsuranceCase
 * BFF for InsuranceCase
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Contract } from './contract';


export interface CustomerWithContracts { 
    id?: number;
    name?: string;
    contracts?: Array<Contract>;
}

